# ------------------- Item Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  name: item
  namespace: micro-obs
  labels:
    app: item
    service: item
spec:
  type: NodePort
  selector:
    app: item
    service: item
  ports:
  - name: http
    protocol: TCP
    port:  8080
    targetPort: http
    nodePort: 30808
---

# ------------------- Item Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: item
  namespace: micro-obs
  labels:
    app: item
    service: item
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
      service: item
  template:
    metadata:
      labels:
        app: item
        service: item
    spec:
      containers:
      - name: item
        image: obitech/micro-obs:v0.2.1
        env:
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent.monitoring.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
        command: ["item"]
        args: ["-r", "redis://redis-item:6379/0"]
        ports:
        - name: http
          containerPort: 8080
---

# ------------------- Item ServiceMonitor ------------------- #
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: item
  namespace: micro-obs
  labels:
    app: item
    service: item
spec:
  selector:
    matchLabels:
      app: item
      service: item
  endpoints:
  - port: http